[phases.setup]
aptPkgs = ["..."]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --prefer-dist"]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache", 
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php -S 0.0.0.0:${PORT:-8080} -t public"
